apiVersion: v1
kind: ConfigMap
metadata:
  name: webserver-demo-cm
  labels:
    app.kubernetes.io/name: webserver-demo
    app.kubernetes.io/instance: webserver-demo
    app.kubernetes.io/version: 1.0.0
data:
# To be mounted on /usr/share/nginx/html
  html: |
    <!doctype html>
    <html lang="en">
    <head>
      <meta charset="utf-8">
      <title>Docker Nginx</title>
    </head>
    <body  style="background-color:green;">
      <h2>Hello from Nginx container</h2>
      <h3>SAHA DevOps Group : This is GitOps demo</h3>
    </body>
    </html>
